### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by abdazzamajhari** [KD0NKS/aprs-is-demo#7]
do you know how can i fetch the data client from aprsc, or the tools what i need to using?
because i need to create an webservices api to build the web apps and mobile apps.. thanks!

**Comment by KD0NKS** [comment]
Part of this depends on which language you are using as to which client library/parser you want to use.  this project is written as a console NodeJS console application as a simple proof of concept using the [js-aprs-is](https://github.com/KD0NKS/js-aprs-is) [npm module](https://www.npmjs.com/package/js-aprs-is) which only supports the TCP connections at the moment.  javAPRSSrvr and aprsc both work the same, so if a client can connect to one, it can connect to the other.  Please reach out if you have more questions.

**Comment by abdazzamajhari** [comment]
> Part of this depends on which language you are using as to which client library/parser you want to use. this project is written as a console NodeJS console application as a simple proof of concept using the [js-aprs-is](https://github.com/KD0NKS/js-aprs-is) [npm module](https://www.npmjs.com/package/js-aprs-is) which only supports the TCP connections at the moment. javAPRSSrvr and aprsc both work the same, so if a client can connect to one, it can connect to the other. Please reach out if you have more questions.

Thanks for the response, Im currently build webservices api with php mysql.. how about http://your-aprs-api:14580/status.json
Do you know, How can i parsing the data clients to database?

**Comment by KD0NKS** [comment]
This project may get you a little closer.  You may have to fork it and update it to run with the current version of PHP: [https://github.com/geeojr/php-aprs](https://github.com/geeojr/php-aprs).  It appears to have some level of mysql already embedded.  You might also check [https://github.com/search?q=php-aprs](https://github.com/search?q=php-aprs) for other existing libraries that may fit your needs.

Unfortunately writing an APRS parser is not a quick easy task as the 1.0.1 spec alone is over 118 pages long.  Starting with even a partially implemented project or finding an implemented parser and converting it to php is probably your best bet if you want to try implementing it on your own.

My approach in multiple languages has always been starting simple by creating a project that is capable of connecting to a server and outputting raw data.  After that you can start playing with pushing raw data into the database or try adding parsing abilities.

From experience in working with real time data, your biggest challenge will be handling the amount of data.  I'm unsure of what stream processing libraries are available for PHP, but I would definitely research them!  This allows you to push data to your database while simultaneously running queries on a stream of data rather than against the database itself.  I know nodejs has plenty such as baconjs.  Your database may also be a big bottle neck depending on your hard drive speed as each write transaction takes a considerable amount of time, You may have to resort to bulk/batch inserts.

**Comment by abdazzamajhari** [comment]
> This project may get you a little closer. You may have to fork it and update it to run with the current version of PHP: https://github.com/geeojr/php-aprs. It appears to have some level of mysql already embedded. You might also check https://github.com/search?q=php-aprs for other existing libraries that may fit your needs.
> 
> Unfortunately writing an APRS parser is not a quick easy task as the 1.0.1 spec alone is over 118 pages long. Starting with even a partially implemented project or finding an implemented parser and converting it to php is probably your best bet if you want to try implementing it on your own.
> 
> My approach in multiple languages has always been starting simple by creating a project that is capable of connecting to a server and outputting raw data. After that you can start playing with pushing raw data into the database or try adding parsing abilities.
> 
> From experience in working with real time data, your biggest challenge will be handling the amount of data. I'm unsure of what stream processing libraries are available for PHP, but I would definitely research them! This allows you to push data to your database while simultaneously running queries on a stream of data rather than against the database itself. I know nodejs has plenty such as baconjs. Your database may also be a big bottle neck depending on your hard drive speed as each write transaction takes a considerable amount of time, You may have to resort to bulk/batch inserts.

Thanks for the response and the advice again... currently im working to tracking my own family with my private server with aprs, and a newbies researcher to programming with the aprs. Thanks again you're so amazing open my mind!

**Comment by KD0NKS** [comment]
Good luck!  My APRS projects are mainly for my own amusement, and hopefully somebody can get some use from them along the way.  For a beginning developer it will definitely present a lot of challenges, but there's a lot of valuable technical lessons within the APRS spec itself (I highly recommend reading it).  Receiving packets, especially from a server is the relatively easy (though technical) part.  Adding the ability to send packets, messages, gps capabilites, mapping ability, etc is where things get complicated very fast, definitely read the guidelines in the spec if and when you get around to that part!
